---
rancher_namespace: cattle-system
rancher_version: v2.5.2
rancher_hostname: "{{ inventory_hostname }}"
rancher_tls_source: letsEncrypt
rancher_letsencrypt_env: production
rancher_ingress_class: traefik
rancher_letsencrypt_email: admin@example.com
