---
- name: Set system hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: yes
  register: hostname_update
  tags:
    - hostname
    - common

- name: Add SSH keys to user
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
    state: present
  with_items: "{{ authorized_ssh_keys }}"
  when: authorized_ssh_keys | length
  tags:
    - ssh
    - common

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes
  tags: common

- name: Install required Ansible System packages
  apt:
    name:
      - python3
      - python3-dev
      - python3-pip
      - python3-apt
    state: latest
  become: yes
  tags:
    - python
    - common

- name: Install OpenShift Python package for Ansible
  pip:
    name: openshift
    umask: "0022"
  become: yes
  tags:
    - python
    - common

- include_tasks: mounts.yaml
  when: additional_mounts | length
  tags:
    - mounts
    - common

- name: Install/Update unattended-upgrades
  apt:
    name: unattended-upgrades
    state: latest
  become: yes
  tags:
    - upgrades
    - common

- name: Perform full system update
  apt:
    name: "*"
    state: latest
    update_cache: yes
  become: yes
  register: apt_update
  tags:
    - updates
    - common

- name: Reboot system to fully apply all changes
  reboot:
    reboot_timeout: 3600
  become: yes
  when: apt_update.changed or hostname_update.changed
  tags: common

- name: Remove packages that are no longer needed
  apt:
    autoremove: yes
    autoclean: yes
  become: yes
  tags:
    - common
    - cleanup
