---
- name: Install Jetstack Helm repository
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
  become: yes
  tags: cert-manager

- name: Deploy cert-manager Chart
  community.kubernetes.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: "{{ certmanager_version }}"
    update_repo_cache: yes
    release_namespace: "{{ certmanager_namespace }}"
    create_namespace: yes
    values:
      installCRDs: yes
    wait: yes
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  become: yes
  register: certmanager
  tags: cert-manager

- name: Wait 2 minutes for cert-manager to be ready
  wait_for:
    timeout: 120
  delegate_to: localhost
  when: certmanager.changed
  tags: cert-manager

- import_tasks: cluster-issuers.yaml
  tags:
    - cluster-issuers
    - cert-manager
